module.exports = {
  key: process.env.googlemap,
  numOfBackgrounds: 8,
  city: {
    name: 'Pale',
    location: '43.8118946,18.5711013',
    radius: '5000',
    categories: {
      accounting: 'Računovodstvo',
      atm: 'ATM',
      bakery: 'Pekara',
      bank: 'Banka',
      bar: 'Bar',
      bus_station: 'Autobuska stanica',
      cafe: 'Kafić',
      car_repair: 'Auto servis',
      car_wash: 'Autopraonica',
      church: 'Crkva',
      clothing_store: 'Butik',
      electronics_store: 'Prodavnica elektronike',
      gas_station: 'Benzinska pumpa',
      grocery_or_supermarket: 'Market',
      gym: 'Teretana',
      home_goods_store: 'Robna kuća',
      hospital: 'Bolnica',
      insurance_agency: 'Agencija za osiguranje',
      local_government_office: 'Gradska uprava',
      lodging: 'Prenoćište',
      museum: 'Muzej',
      night_club: 'Noćni klub',
      park: 'Park',
      parking: 'Parking',
      pharmacy: 'Apoteka',
      police: 'Policijska stanica',
      post_office: 'Pošta',
      restaurant: 'Restoran',
      school: 'Škola',
      shoe_store: 'Prodavnica obuće',
      shopping_mall: 'Trgovački centar',
      stadium: 'Sportski stadion',
      store: 'Prodavnica',
      travel_agency: 'Turistička agencija',
      university: 'Fakultet',
      veterinary_care: 'Veterinarska ambulanta'
    }
  }
}
